description: >
  Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
docker:
  - image: 'buildpack-deps:<<parameters.tag>>'
parameters:
  tag:
    default: bionic
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/circleci/node/tags
    type: string
